spring:
    application:
        name: Translator

    datasource:
        generate-unique-name: false
        name: translator
        url: jdbc:h2:mem:translator
        username: sa

yandex:
    translate:
        api:
            key: <KEY>
